scene_buffer:
  ros__parameters:
    robot_names:
      - robot_1
      - robot_2
    
    padding: 0.05

    collision_maps:
      robot_1:
        collision_robots:
          - robot_2
      robot_2:
        collision_robots:
          - robot_1
