scene_buffer:
  ros__parameters:
    robot_names:
      - robot_1
      - robot_2
      - robot_3
      - robot_4
    
    padding: 0.02
    delay_duration: 0.1
    pub_obstacles: true
    obstacle_pub_step: 3

    pos_diff_min: 0.02
    pos_diff_max: 0.05
    rot_diff_min: 0.002
    rot_diff_max: 0.005

    collision_maps:
      robot_1:
        collision_robots:
          - robot_2
          - robot_3
      robot_2:
        collision_robots:
          - robot_1
          - robot_4
      robot_3:
        collision_robots:
          - robot_1
          - robot_4
      robot_4:
        collision_robots:
          - robot_2
          - robot_3

compute_traj_length:
  ros__parameters:
    robot_names:
      - robot_1
      - robot_2
      - robot_3
      - robot_4